apiVersion: v1
kind: Service
metadata:
  name: sdc-mapr
  labels:
    app: sdc-mapr
spec:
  type: NodePort
  ports:
  - name: http
    port: 18630
    targetPort: 18630
    nodePort: 31910
    protocol: TCP
  selector:
    app: sdc-mapr
